name: Build and Test

on: [push, pull_request]

env:
  CONVERT: USD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.0

    - name: Set up Python
      uses: actions/setup-python@v2.3.0
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install Flask
        pip install Flask-CORS
        pip install requests

    - name: Run tests
      run: |
        python -m unittest discover
      env:
        CONVERT: ${{ env.CONVERT }}
