name: CI/CD Flask API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        pip install requests_mock
        pip install flask
        pip install flask-cors
        pip install requests

    - name: Start API Server
      run: |
        set FLASK_APP=retrieve_data.py
        FLASK_PID=$!
        flask run --port 5000 &

        echo "FLASK_PID=$FLASK_PID" >> $GITHUB_ENV

    - name: Test API
      run: |
        python test_retrieve_data.py
